#!/usr/bin/env bash

#setting environment variables for nginx and mono
export PATH=$HOME/nginx/sbin:$PATH
export PATH=$HOME/mono/bin:$PATH
export LD_LIBRARY_PATH=$HOME/mono/lib:$LD_LIBRARY_PATH

#generating nginx.conf with current port and home directory
erb $HOME/nginx/conf/nginx.conf.erb > $HOME/nginx/conf/nginx.conf

#starting nginx and mono fastcgi
$HOME/nginx/sbin/nginx
$HOME/mono/bin/fastcgi-mono-server4 /applications=/:$HOME/www/ /socket=tcp:127.0.0.1:9000 &

#keep script running until nginx stops
#sleep 1
#while kill -0 "$(cat $HOME/nginx/logs/nginx.pid)"; do
#	sleep 0.5
#done